# Generated by Django 3.2 on 2023-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
